executable = /afs/desy.de/user/d/dudarboh/analysis/TrackLength/HarmonicAndConsistency/job/job.sh

initialdir = /nfs/dust/ilc/user/dudarboh/jobs
arguments = $(file) $(ClusterId) $(ProcId)
max_materialize = 500
log = ../log/$(ClusterId)_$(ProcId).log
output = ../out/$(ClusterId)_$(ProcId).out
error = ../err/$(ClusterId)_$(ProcId).err
request_cpus = 1
request_memory = 1GB
request_disk = 10KB

queue file from /afs/desy.de/user/d/dudarboh/analysis/data/REC/250GeV/2f_Z_hadronic_E250_eLpR.txt
